### ISSUE TITLE
Issue adding additional markers to similar clusters

### ISSUE THREAD

**Issue by franpcozar** [DrCytometer/ClusterID#1]
Hi, very useful package! I tried to add variable markers to my similar clusters, but in the third for loop of the code I got the following error:

```
Error in if (abs(cluster.summary[as.numeric(names(position.in.cluster.list)),  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In `[.tbl_df`(cluster.summary, as.numeric(names(position.in.cluster.list)),  :
  NAs introduced by coercion
2: In `[.tbl_df`(cluster.summary, as.numeric(names(position.in.cluster.list)),  :
  NAs introduced by coercion
```

It seems that it does not find the position of the cluster in `position.in.cluster.list` and then it introduces "NAs"

Thank you!

**Comment by DrCytometer** [comment]
Hi,
Any chance you could share some data that produces this error? Saving the stuff you're working on as .rdata would be the simplest. If that works for you, you can send it to me at ob240@cam.ac.uk (e.g., WeTransfer if it's big).

**Comment by DrCytometer** [comment]
If you're using a CSV file as input, that's fine by email.

**Comment by DrCytometer** [comment]
Now fixed in the updated cluster_id script.
